{
    "name": "Foodics Connector",
    "version": "19.0.1.0.0",
    "summary": "Bidirectional synchronization bridge between Odoo and Foodics POS",
    "description": """
        Connect Odoo with Foodics API v2 for products, categories, customers,
        orders, inventory, taxes, webhooks, mapping, monitoring, and retries.
    """,
    "category": "Sales/Point of Sale",
    "author": "Woledge",
    "depends": [
        "account",
        "contacts",
        "mail",
        "point_of_sale",
        "product",
        "sale_management",
        "stock",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/foodics_webhook_events.xml",
        "data/default_mappings.xml",
        "data/cron_data.xml",
        "views/foodics_connection_views.xml",
        "views/foodics_mapping_views.xml",
        "views/foodics_sync_log_views.xml",
        "views/foodics_webhook_views.xml",
        "views/product_views.xml",
        "views/partner_views.xml",
        "views/dashboard_views.xml",
        "wizards/wizard_test_connection_views.xml",
        "wizards/wizard_resync_views.xml",
        "report/reconciliation_report.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
