{
    'name': 'Advanced Sales Reports',
    'version': '18.0.1.0.0',
    'category': 'Sales',
    'summary': """This Module Helps to Generate Advanced sales reports""",
    'description': """This module helps you to print reports like Sales Analysis, 
     Sales By Category, Sales Indent, Sales Invoice ,Product Profit ,
     Hourly Sales in PDF and XLSX format.""",
    'author': "Ibrahim Elmasry",
    'website': "https://www.woledge.com",
    'depends': ['sale_management', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/sale_report_advance_views.xml',
        'wizard/sale_report_invoice_views.xml',
        'wizard/sale_report_analysis_views.xml',
        'wizard/sale_report_weekly_views.xml',
        'wizard/sale_report_category_views.xml',
        'wizard/sale_report_indent_views.xml',
        'views/sale_report_advanced_views.xml',
        'report/sale_advanced_reports.xml',
        'report/invoice_analysis_templates.xml',
        'report/sales_indent_templates.xml',
        'report/sale_profit_templates.xml',
        'report/sales_category_templates.xml',
        'report/sales_analysis_templates.xml',
        'report/sales_weekly_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sale_report_advanced/static/src/js/action_manager.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
