from . import hr_version
from . import hr_payslip
from . import hr_salary_rule
from . import resource_calendar_leaves
from . import rm_overtime_rule
from . import rm_lateness_rule
from . import rm_absence_rule
from . import rm_attendance_policy
from . import rm_attendance_sheet
