import random
import string
from odoo import fields, models, api, _
from odoo.exceptions import UserError


class EbookCode(models.Model):
    _name = 'ebook.code'
    _description = 'E-Book Access Code'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc'

    name = fields.Char(string='Code', required=True, tracking=True, index=True)
    product_tmpl_id = fields.Many2one('product.template', string='E-Book', required=True, tracking=True)
    partner_id = fields.Many2one('res.partner', string='Customer', tracking=True)
    order_id = fields.Many2one('sale.order', string='Sale Order')
    state = fields.Selection([
        ('available', 'Available'),
        ('assigned', 'Assigned'),
        ('used', 'Used'),
        ('expired', 'Expired'),
    ], string='Status', default='available', tracking=True, index=True)
    generated_by = fields.Selection([
        ('auto', 'Auto Generated'),
        ('manual', 'Manual'),
    ], string='Generated By', default='auto')
    access_count = fields.Integer(string='Access Count', default=0)
    max_access = fields.Integer(string='Max Access', default=1, help='Maximum number of times this code can be used')
    create_date = fields.Datetime(string='Created Date', readonly=True)
    used_date = fields.Datetime(string='Used Date', readonly=True)
    expiry_date = fields.Datetime(string='Expiry Date', help='Optional: when this code expires')

    @api.model
    def _generate_random_code(self):
        """Generate a unique random code: EBK-XXXX-XXXX-XXXX"""
        chars = string.ascii_uppercase + string.digits
        while True:
            code = 'EBK-' + '-'.join(
                ''.join(random.choices(chars, k=4)) for _ in range(3)
            )
            if not self.search_count([('name', '=', code)]):
                return code

    @api.model
    def generate_codes(self, product_tmpl_id, count, generation_mode='auto', manual_codes=None):
        """Generate codes for a product. Returns created records."""
        if generation_mode == 'auto':
            codes = []
            for _ in range(count):
                code = self._generate_random_code()
                codes.append(self.create({
                    'name': code,
                    'product_tmpl_id': product_tmpl_id,
                    'generated_by': 'auto',
                }))
            return codes
        elif generation_mode == 'manual':
            if not manual_codes:
                raise UserError(_('No manual codes provided.'))
            codes = []
            for raw_code in manual_codes:
                code = raw_code.strip()
                if not code:
                    continue
                if self.search_count([('name', '=', code)]):
                    raise UserError(_('Code already exists: %s') % code)
                codes.append(self.create({
                    'name': code,
                    'product_tmpl_id': product_tmpl_id,
                    'generated_by': 'manual',
                }))
            return codes

    def action_assign(self, partner_id, order_id):
        """Assign a code to a customer from an order."""
        self.ensure_one()
        if self.state != 'available':
            return False
        self.write({
            'partner_id': partner_id,
            'order_id': order_id,
            'state': 'assigned',
        })
        return True

    def action_use(self):
        """Mark a code as used — called when customer opens the book."""
        self.ensure_one()
        if self.state == 'used':
            if self.access_count >= self.max_access:
                return False
        if self.state not in ('assigned', 'used'):
            return False
        vals = {'access_count': self.access_count + 1}
        if self.access_count == 0:
            vals['used_date'] = fields.Datetime.now()
        if self.access_count + 1 >= self.max_access:
            vals['state'] = 'used'
        self.write(vals)
        return True

    def action_assign_and_expire(self, partner_id, order_id):
        """Assign a code to a customer AND expire it immediately.
        This is the one-time use pattern: the code is sent via email
        and can never be reused by anyone else."""
        self.ensure_one()
        if self.state != 'available':
            return False
        self.write({
            'partner_id': partner_id,
            'order_id': order_id,
            'state': 'expired',  # immediately expired — one-time use
            'used_date': fields.Datetime.now(),
        })
        return True

    def action_reset(self):
        """Reset a code back to available."""
        self.write({
            'state': 'available',
            'partner_id': False,
            'order_id': False,
            'access_count': 0,
            'used_date': False,
        })

    def action_expire(self):
        """Mark code as expired."""
        self.write({'state': 'expired'})
